import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { LogOut, Menu, FileText, Users, Calendar, Sparkles, History, Copy, Download, Trash2, Clock, Sun, Moon, Brain } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { generatePRD } from '../lib/gemini';
import { useTheme } from '../context/ThemeContext';
// @ts-ignore
import html2pdf from 'html2pdf.js';

interface SavedPRD {
    id: string;
    title: string;
    content: string;
    created_at: string;
}

export function PRDGenerator() {
    const [sidebarOpen, setSidebarOpen] = useState(false);
    const [userName, setUserName] = useState('');
    const [userEmail, setUserEmail] = useState('');
    const [productIdea, setProductIdea] = useState('');
    const [generatedPRD, setGeneratedPRD] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [savedPRDs, setSavedPRDs] = useState<SavedPRD[]>([]);
    const [copied, setCopied] = useState(false);
    const [selectedPRD, setSelectedPRD] = useState<SavedPRD | null>(null);
    const { theme, toggleTheme } = useTheme();
    const navigate = useNavigate();

    useEffect(() => {
        const fetchUserAndPRDs = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (user) {
                setUserEmail(user.email || '');
                setUserName(user.user_metadata?.full_name || user.user_metadata?.name || user.email?.split('@')[0] || 'User');

                // Fetch PRDs from Supabase
                const { data, error } = await supabase
                    .from('prds')
                    .select('*')
                    .eq('user_id', user.id)
                    .order('created_at', { ascending: false });

                if (data && !error) {
                    setSavedPRDs(data);
                }
            }
        };
        fetchUserAndPRDs();
    }, []);

    const handleGenerate = async () => {
        if (!productIdea.trim()) return;
        setLoading(true);
        setError(null);
        setGeneratedPRD('');
        setSelectedPRD(null);
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) throw new Error('You must be logged in to generate PRDs');

            const result = await generatePRD(productIdea);
            setGeneratedPRD(result);

            // Save to Supabase
            const { data, error } = await supabase
                .from('prds')
                .insert([{
                    user_id: user.id,
                    title: productIdea,
                    content: result
                }])
                .select()
                .single();

            if (error) throw error;
            if (data) {
                setSavedPRDs([data, ...savedPRDs]);
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to generate PRD');
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = async () => {
        const content = selectedPRD?.content || generatedPRD;
        await navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const content = selectedPRD?.content || generatedPRD;
        const idea = selectedPRD?.title || productIdea;

        const element = document.createElement('div');
        element.innerHTML = `
            <div style="padding: 40px; font-family: sans-serif; color: #333; line-height: 1.6;">
                <h1 style="color: #ef4444; border-bottom: 2px solid #ef4444; padding-bottom: 10px;">PRD: ${idea}</h1>
                <p style="color: #666; font-size: 12px;">Generated by 3.0 Labs PM Agent on ${new Date().toLocaleDateString()}</p>
                <div style="margin-top: 20px; white-space: pre-wrap;">${content}</div>
            </div>
        `;

        const opt = {
            margin: 10,
            filename: `PRD-${idea.substring(0, 30).replace(/[^a-zA-Z0-9]/g, '_')}.pdf`,
            image: { type: 'jpeg' as 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2 },
            jsPDF: { unit: 'mm' as 'mm', format: 'a4' as 'a4', orientation: 'portrait' as 'portrait' }
        };

        html2pdf().set(opt).from(element).save();
    };

    const handleDelete = async (id: string) => {
        try {
            const { error } = await supabase
                .from('prds')
                .delete()
                .eq('id', id);

            if (error) throw error;

            setSavedPRDs(savedPRDs.filter(p => p.id !== id));
            if (selectedPRD?.id === id) {
                setSelectedPRD(null);
                setGeneratedPRD('');
            }
        } catch (err) {
            console.error('Delete error:', err);
            setError('Failed to delete PRD');
        }
    };

    const handleSignOut = async () => {
        await supabase.auth.signOut();
        navigate('/auth');
    };

    const displayContent = selectedPRD?.content || generatedPRD;

    return (
        <div className={`flex h-screen w-full overflow-hidden transition-colors duration-300 ${theme === 'dark' ? 'bg-[#050505] text-white' : 'bg-slate-50 text-slate-900'}`}>
            {sidebarOpen && (
                <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-30 md:hidden" onClick={() => setSidebarOpen(false)} />
            )}

            {/* Sidebar */}
            <aside className={`fixed inset-y-0 left-0 z-40 w-64 border-r transform transition-transform duration-300 ease-in-out flex flex-col pt-6 pb-4 ${theme === 'dark' ? 'bg-[#0B0C10] border-white/10' : 'bg-white border-slate-200'} ${sidebarOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}`}>
                <div className="flex items-center justify-between px-6 mb-8 relative">
                    <img src="/logo.png" alt="3.0Labs" className="h-10 w-auto object-contain" />
                    <button className="md:hidden text-gray-400 hover:text-white" onClick={() => setSidebarOpen(false)}>&times;</button>
                    {/* Tiny Sidebar Robot */}
                    <div className="absolute -top-4 -right-2 w-8 h-8 opacity-40">
                        <div className="w-6 h-4 bg-[#1a1c24] border-b border-red-500/50 rounded-b-lg flex items-center justify-center relative">
                            <div className="flex gap-1">
                                <div className="w-0.5 h-0.5 bg-red-500 rounded-full"></div>
                                <div className="w-0.5 h-0.5 bg-red-500 rounded-full"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="px-6 mb-6">
                    <div className="font-semibold text-white">{userName || "Your Name"}</div>
                    <div className="text-xs text-gray-400">{userEmail || "your@email.com"}</div>
                </div>
                <nav className="flex-1 overflow-y-auto custom-scrollbar py-2">
                    <ul className="space-y-1 px-3">
                        <li className="px-3 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider">Meetings</li>
                        <li><Link to="/summarizer" className="flex items-center text-gray-300 hover:text-white hover:bg-white/5 font-medium rounded-xl px-3 py-2.5 transition-colors"><span className="mr-3 text-lg opacity-80">🏠</span> Home</Link></li>
                        <li><Link to="/history" className="flex items-center text-gray-300 hover:text-white hover:bg-white/5 font-medium rounded-xl px-3 py-2.5 transition-colors"><History className="w-5 h-5 mr-3 opacity-80" /> Meeting History</Link></li>
                        <li>
                            <Link to="/ai-chat" className="flex items-center text-gray-300 hover:text-white hover:bg-white/5 font-medium rounded-xl px-3 py-2.5 transition-colors">
                                <Brain className="w-5 h-5 mr-3 opacity-80" /> 3.0 Agent
                            </Link>
                        </li>
                        <li className="pt-4 px-3 py-2 text-xs font-semibold text-gray-500 uppercase tracking-wider">PM Agent</li>
                        <li><Link to="/pm-dashboard" className="flex items-center text-gray-300 hover:text-white hover:bg-white/5 font-medium rounded-xl px-3 py-2.5 transition-colors"><Sparkles className="w-5 h-5 mr-3 opacity-80" /> PM Dashboard</Link></li>
                        <li><Link to="/prd-generator" className="flex items-center text-white bg-white/10 font-medium rounded-xl px-3 py-2.5 transition-colors"><FileText className="w-5 h-5 mr-3 text-red-500 animate-pulse" /> PRD Generator</Link></li>
                        <li><Link to="/user-stories" className="flex items-center text-gray-300 hover:text-white hover:bg-white/5 font-medium rounded-xl px-3 py-2.5 transition-colors"><Users className="w-5 h-5 mr-3 opacity-80" /> User Stories</Link></li>
                        <li><Link to="/sprint-planner" className="flex items-center text-gray-300 hover:text-white hover:bg-white/5 font-medium rounded-xl px-3 py-2.5 transition-colors"><Calendar className="w-5 h-5 mr-3 opacity-80" /> Sprint Planner</Link></li>
                    </ul>
                </nav>
                <div className="px-6 space-y-2">
                    <button onClick={toggleTheme} className="flex items-center w-full text-gray-400 hover:text-red-400 hover:bg-red-500/10 px-3 py-2.5 rounded-xl transition-all group">
                        {theme === 'dark' ? <Sun className="w-5 h-5 mr-3 group-hover:rotate-180 transition-transform duration-500" /> : <Moon className="w-5 h-5 mr-3 group-hover:-rotate-12 transition-transform duration-500" />}
                        {theme === 'dark' ? 'Light Mode' : 'Dark Mode'}
                    </button>
                    <button onClick={handleSignOut} className="flex items-center w-full text-gray-400 hover:text-red-400 hover:bg-red-500/10 px-3 py-2.5 rounded-xl transition-colors"><LogOut className="w-5 h-5 mr-3" /> Sign Out</button>
                </div>
            </aside>

            <button className="md:hidden fixed top-4 right-4 z-50 bg-[#0B0C10] border border-white/10 rounded-full p-2 shadow-lg" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Open menu">
                <Menu className="w-6 h-6 text-white" />
            </button>

            <div className={`flex-1 flex flex-col md:ml-64 h-screen overflow-hidden relative transition-colors duration-300 ${theme === 'dark' ? 'bg-[#050505] text-white' : 'bg-slate-50 text-slate-900'}`}>
                {/* Massive Background Branding Text - RED THEME */}
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden z-0 select-none">
                    <div className="text-[20vw] font-black text-red-500/[0.03] whitespace-nowrap leading-none tracking-tighter transform -rotate-12 select-none animate-pulse-slow">
                        3.0LABS
                    </div>
                </div>

                {/* Roaming Spy Robot */}
                <div className="fixed inset-0 pointer-events-none z-0 overflow-hidden">
                    <div className="absolute w-24 h-16 animate-robot-roam opacity-20" style={{ animationDelay: '2s' }}>
                        <div className="w-16 h-10 bg-[#1a1c24] border-b-2 border-red-500/50 rounded-b-2xl shadow-[0_5px_15px_rgba(239,68,68,0.2)] flex items-center justify-center relative">
                            <div className="flex gap-2">
                                <div className="w-1.5 h-1.5 bg-red-500 rounded-full animate-robot-blink"></div>
                                <div className="w-1.5 h-1.5 bg-red-500 rounded-full animate-robot-blink"></div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Ambient orbs - RED THEME */}
                <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-red-600/20 rounded-full blur-[120px] animate-float pointer-events-none"></div>
                <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-80 h-80 bg-red-900/20 rounded-full blur-[100px] animate-float-slow pointer-events-none"></div>
                <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-red-500/50 to-transparent animate-shimmer z-20"></div>

                <header className="flex items-center justify-between px-4 md:px-10 py-6 bg-[#0B0C10]/80 backdrop-blur-xl border-b border-white/5 z-30 flex-shrink-0">
                    <div>
                        <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-3">
                            <FileText className="w-7 h-7 text-red-500 animate-pulse" />
                            PRD Generator
                        </h1>
                        <p className="text-gray-400 text-sm mt-1">Generate comprehensive Product Requirements Documents with AI</p>
                    </div>
                </header>

                <div className="flex-1 flex flex-col xl:flex-row overflow-hidden">
                    {/* Main area */}
                    <div className="flex-1 overflow-y-auto px-4 md:px-10 py-8 z-10">
                        {/* Input */}
                        <div className="mb-8 p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl animate-fade-in-up">
                            <label className="block font-semibold text-white text-lg mb-3 tracking-tight">Describe your product or feature idea</label>
                            <textarea
                                value={productIdea}
                                onChange={e => setProductIdea(e.target.value)}
                                placeholder="e.g. An AI-powered meeting summarizer that automatically generates action items and sends them to Slack..."
                                className="w-full h-32 px-4 py-3 bg-black/40 border border-white/10 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/50 focus:border-red-500 transition-all text-white placeholder-gray-600 resize-none"
                            />
                            <div className="flex items-center justify-between mt-4">
                                <span className="text-xs text-gray-500">{productIdea.length} characters</span>
                                <button
                                    onClick={handleGenerate}
                                    disabled={loading || !productIdea.trim()}
                                    className="px-8 py-3 bg-gradient-to-r from-red-600 to-red-800 text-white font-semibold rounded-xl shadow-[0_0_20px_rgba(239,68,68,0.3)] hover:shadow-[0_0_30px_rgba(239,68,68,0.5)] hover:from-red-500 hover:to-red-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                                >
                                    {loading ? (
                                        <>
                                            <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                                            Generating...
                                        </>
                                    ) : (
                                        <>
                                            <Sparkles className="w-5 h-5" />
                                            Generate PRD
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>

                        {error && (
                            <div className="mb-6 p-4 bg-red-500/10 border border-red-500/30 text-red-400 rounded-xl flex items-center justify-between">
                                <span>{error}</span>
                                <button onClick={() => setError(null)} className="text-red-400 hover:text-white">&times;</button>
                            </div>
                        )}

                        {loading && (
                            <div className="mb-8 p-8 bg-red-500/10 border border-red-500/30 rounded-2xl flex flex-col items-center justify-center space-y-4 animate-pulse">
                                <div className="w-12 h-12 border-4 border-red-500 border-t-transparent rounded-full animate-spin"></div>
                                <div className="text-red-400 font-semibold text-lg">Generating your PRD...</div>
                                <div className="text-gray-400 text-sm">This may take 15-30 seconds for a comprehensive document.</div>
                            </div>
                        )}

                        {displayContent && !loading && (
                            <div className="mb-8 p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl animate-fade-in-up">
                                <div className="flex items-center justify-between mb-4">
                                    <div className="font-semibold text-red-500 text-lg flex items-center">
                                        <div className="w-2 h-2 bg-red-600 rounded-full mr-3 animate-pulse"></div>
                                        {selectedPRD ? `PRD: ${selectedPRD.title.substring(0, 50)}...` : 'Generated PRD'}
                                    </div>
                                    <div className="flex gap-2">
                                        <button onClick={handleCopy} className="p-2 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors" title="Copy">
                                            <Copy className="w-4 h-4" />
                                        </button>
                                        <button onClick={handleDownload} className="p-2 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors" title="Download">
                                            <Download className="w-4 h-4" />
                                        </button>
                                    </div>
                                </div>
                                {copied && <div className="mb-3 text-sm text-emerald-400">✓ Copied to clipboard!</div>}
                                <div className="text-gray-300 leading-relaxed whitespace-pre-wrap text-sm prose-sm max-w-none">
                                    {displayContent}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* History sidebar */}
                    <aside className="hidden xl:flex w-80 bg-[#0B0C10]/80 backdrop-blur-md border-t xl:border-t-0 xl:border-l border-white/5 px-6 py-8 flex-col z-20 overflow-y-auto">
                        <h3 className="text-lg font-bold text-white tracking-tight mb-6 flex items-center gap-2">
                            <Clock className="w-5 h-5 text-gray-400" />
                            PRD History
                        </h3>
                        {savedPRDs.length === 0 ? (
                            <div className="text-gray-500 text-sm text-center py-8">No PRDs generated yet</div>
                        ) : (
                            <div className="space-y-3">
                                {savedPRDs.map(prd => (
                                    <div
                                        key={prd.id}
                                        className={`p-4 rounded-xl border cursor-pointer transition-all group ${selectedPRD?.id === prd.id ? 'bg-red-500/10 border-red-500/30' : 'bg-white/5 border-white/10 hover:bg-white/[0.07]'}`}
                                        onClick={() => { setSelectedPRD(prd); setGeneratedPRD(''); }}
                                    >
                                        <div className="font-medium text-white text-sm truncate mb-1">{prd.title}</div>
                                        <div className="text-xs text-gray-500 flex items-center justify-between">
                                            <span>{new Date(prd.created_at).toLocaleDateString()}</span>
                                            <button
                                                onClick={e => { e.stopPropagation(); handleDelete(prd.id); }}
                                                className="p-1 text-gray-500 hover:text-red-400 rounded opacity-0 group-hover:opacity-100 transition-opacity"
                                            >
                                                <Trash2 className="w-3.5 h-3.5" />
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </aside>
                </div>
            </div>
        </div>
    );
}
