import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Calendar, Sparkles, Copy, Download, Trash2, Clock } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { generateSprintPlan } from '../lib/gemini';
import { useTheme } from '../context/ThemeContext';
// @ts-ignore
import html2pdf from 'html2pdf.js';

interface SavedSprint {
    id: string;
    backlog: string;
    duration: string;
    content: string;
    created_at: string;
}

export function SprintPlanner() {
    const [backlogItems, setBacklogItems] = useState('');
    const [sprintDuration, setSprintDuration] = useState('2 weeks');
    const [generatedPlan, setGeneratedPlan] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [savedSprints, setSavedSprints] = useState<SavedSprint[]>([]);
    const [copied, setCopied] = useState(false);
    const [selectedSprint, setSelectedSprint] = useState<SavedSprint | null>(null);
    const { theme } = useTheme();
    const navigate = useNavigate();

    useEffect(() => {
        const fetchUserAndSprints = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (user) {
                const { data, error } = await supabase
                    .from('sprint_plans')
                    .select('*')
                    .eq('user_id', user.id)
                    .order('created_at', { ascending: false });

                if (data && !error) {
                    setSavedSprints(data);
                }
            } else {
                navigate('/auth');
            }
        };
        fetchUserAndSprints();
    }, [navigate]);

    const handleGenerate = async () => {
        if (!backlogItems.trim()) return;
        setLoading(true); setError(null); setGeneratedPlan(''); setSelectedSprint(null);
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) throw new Error('You must be logged in to plan sprints');

            const result = await generateSprintPlan(backlogItems, sprintDuration);
            setGeneratedPlan(result);

            const { data, error } = await supabase
                .from('sprint_plans')
                .insert([{
                    user_id: user.id,
                    backlog: backlogItems,
                    duration: sprintDuration,
                    content: result
                }])
                .select()
                .single();

            if (error) throw error;
            if (data) {
                setSavedSprints([data, ...savedSprints]);
            }
        } catch (err) { setError(err instanceof Error ? err.message : 'Failed to generate sprint plan'); }
        finally { setLoading(false); }
    };

    const handleCopy = async () => { await navigator.clipboard.writeText(selectedSprint?.content || generatedPlan); setCopied(true); setTimeout(() => setCopied(false), 2000); };
    
    const handleDownload = () => {
        const content = selectedSprint?.content || generatedPlan;
        const duration = selectedSprint?.duration || sprintDuration;
        const element = document.createElement('div');
        element.innerHTML = `<div style="padding: 40px; font-family: sans-serif; color: #333; line-height: 1.6;"><h1 style="color: #ef4444; border-bottom: 2px solid #ef4444; padding-bottom: 10px;">Sprint Plan: ${duration}</h1><p style="color: #666; font-size: 12px;">Generated by 3.0 Labs PM Agent on ${new Date().toLocaleDateString()}</p><div style="margin-top: 20px; white-space: pre-wrap;">${content}</div></div>`;
        const opt = { margin: 10, filename: `Sprint-Plan-${new Date().toISOString().split('T')[0]}.pdf`, image: { type: 'jpeg' as 'jpeg', quality: 0.98 }, html2canvas: { scale: 2 }, jsPDF: { unit: 'mm' as 'mm', format: 'a4' as 'a4', orientation: 'portrait' as 'portrait' } };
        html2pdf().set(opt).from(element).save();
    };

    const handleDelete = async (id: string) => {
        try {
            const { error } = await supabase.from('sprint_plans').delete().eq('id', id);
            if (error) throw error;
            setSavedSprints(savedSprints.filter(s => s.id !== id));
            if (selectedSprint?.id === id) { setSelectedSprint(null); setGeneratedPlan(''); }
        } catch (err) {
            setError('Failed to delete sprint plan');
        }
    };

    const displayContent = selectedSprint?.content || generatedPlan;

    return (
        <>
            <div className="flex-1 flex flex-col h-screen overflow-hidden relative px-0 sm:px-0">
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden z-0 select-none">
                    <div className="text-[20vw] font-black text-red-500/[0.03] whitespace-nowrap leading-none tracking-tighter transform -rotate-12 select-none animate-pulse-slow">
                        3.0LABS
                    </div>
                </div>

                <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-red-600/20 rounded-full blur-[120px] animate-float pointer-events-none" />
                <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-80 h-80 bg-red-900/15 rounded-full blur-[100px] animate-float-slow pointer-events-none" />
                <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-red-500/50 to-transparent animate-shimmer z-20" />
                <header className={`flex flex-col sm:flex-row items-start sm:items-center justify-between px-4 md:px-10 py-4 sm:py-6 backdrop-blur-xl border-b z-30 flex-shrink-0 gap-2 ${theme === 'dark' ? 'bg-[#0B0C10]/80 border-red-500/10' : 'bg-white/80 border-slate-200'}`}>
                    <div><h1 className={`text-xl sm:text-2xl font-bold tracking-tight flex items-center gap-3 ${theme === 'dark' ? 'text-white' : 'text-slate-900'}`}><Calendar className="w-6 h-6 sm:w-7 sm:h-7 text-red-500 animate-pulse" />Sprint Planner</h1>
                        <p className="text-gray-400 text-xs sm:text-sm mt-1">AI-powered sprint planning with priorities and story points</p></div>
                </header>

                <div className="flex-1 flex flex-col xl:flex-row overflow-hidden">
                    <div className="flex-1 overflow-y-auto px-4 md:px-10 py-8 z-10 custom-scrollbar">
                        <div className="mb-8 p-4 sm:p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl animate-fade-in-up">
                            <label className="block font-semibold text-white text-lg mb-3">Backlog Items</label>
                            <textarea value={backlogItems} onChange={e => setBacklogItems(e.target.value)} placeholder={"Enter your backlog items (one per line):\n- User login & registration\n- Dashboard analytics page\n- Email notification system\n- Payment integration\n- Profile settings page"} className="w-full h-40 px-4 py-3 bg-black/40 border border-white/10 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/50 text-white placeholder-gray-600 resize-none" />
                            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mt-4 gap-4">
                                <div className="flex items-center gap-3">
                                    <label className="text-sm text-gray-400">Sprint Duration:</label>
                                    <select value={sprintDuration} onChange={e => setSprintDuration(e.target.value)} className="bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-white text-sm focus:ring-2 focus:ring-red-500/50 focus:outline-none">
                                        <option value="1 week">1 Week</option>
                                        <option value="2 weeks">2 Weeks</option>
                                        <option value="3 weeks">3 Weeks</option>
                                        <option value="4 weeks">4 Weeks</option>
                                    </select>
                                </div>
                                <button onClick={handleGenerate} disabled={loading || !backlogItems.trim()} className="w-full sm:w-auto px-8 py-3 bg-gradient-to-r from-red-600 to-red-800 text-white font-semibold rounded-xl shadow-[0_0_20px_rgba(239,68,68,0.3)] hover:shadow-[0_0_30px_rgba(239,68,68,0.5)] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2">
                                    {loading ? <><div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />Planning...</> : <><Sparkles className="w-5 h-5" />Generate Plan</>}
                                </button>
                            </div>
                        </div>
                        {error && <div className="mb-6 p-4 bg-red-500/10 border border-red-500/30 text-red-400 rounded-xl flex items-center justify-between uppercase text-xs font-bold tracking-widest"><span>{error}</span><button onClick={() => setError(null)}>&times;</button></div>}
                        {displayContent && !loading && (
                            <div className="mb-8 p-4 sm:p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl animate-fade-in-up">
                                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-4 gap-2">
                                    <div className="font-semibold text-red-500 text-lg flex items-center"><div className="w-2 h-2 bg-red-600 rounded-full mr-3 animate-pulse" />{selectedSprint ? `Sprint: ${selectedSprint.duration}` : 'Generated Sprint Plan'}</div>
                                    <div className="flex flex-wrap gap-2">
                                        <button onClick={handleCopy} className="p-2 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg" title="Copy"><Copy className="w-4 h-4" /></button>
                                        <button onClick={handleDownload} className="p-2 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg" title="Download"><Download className="w-4 h-4" /></button>
                                    </div>
                                </div>
                                {copied && <div className="mb-3 text-sm text-emerald-400">Γ£ô Copied!</div>}
                                <div className="text-gray-300 leading-relaxed whitespace-pre-wrap text-sm">{displayContent}</div>
                            </div>
                        )}
                    </div>
                    <aside className="hidden xl:flex w-full xl:w-80 bg-[#0B0C10]/80 backdrop-blur-md border-l border-red-500/10 px-4 sm:px-6 py-8 flex-col z-20 overflow-y-auto custom-scrollbar">
                        <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2"><Clock className="w-5 h-5 text-gray-400" />Sprint History</h3>
                        {savedSprints.length === 0 ? <div className="text-gray-500 text-sm text-center py-8">No sprints yet</div> :
                            <div className="space-y-3">{savedSprints.map(s => (
                                <div key={s.id} className={`p-4 rounded-xl border cursor-pointer transition-all group ${selectedSprint?.id === s.id ? 'bg-red-500/10 border-red-500/30' : 'bg-white/5 border-white/10 hover:bg-white/[0.07]'}`} onClick={() => { setSelectedSprint(s); setGeneratedPlan(''); }}>
                                    <div className="font-medium text-white text-sm truncate mb-1">{s.duration} sprint</div>
                                    <div className="text-xs text-gray-500 mb-1 truncate">{s.backlog.substring(0, 60)}...</div>
                                    <div className="text-xs text-gray-500 flex items-center justify-between"><span>{new Date(s.created_at).toLocaleDateString()}</span>
                                        <button onClick={e => { e.stopPropagation(); handleDelete(s.id); }} className="p-1 text-gray-500 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"><Trash2 className="w-3.5 h-3.5" /></button>
                                    </div>
                                </div>
                            ))}</div>}
                    </aside>
                </div>
            </div>
            <style>{`
                .custom-scrollbar::-webkit-scrollbar { width: 4px; }
                .custom-scrollbar::-webkit-scrollbar-track { background: rgba(255, 255, 255, 0.02); }
                .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.1); border-radius: 10px; }
                .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(255, 255, 255, 0.2); }
            `}</style>
        </>
    );
}
