import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Users, Sparkles, Copy, Download, Trash2, Clock } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { generateUserStories } from '../lib/gemini';
import { useTheme } from '../context/ThemeContext';
// @ts-ignore
import html2pdf from 'html2pdf.js';

interface SavedStories {
    id: string;
    feature: string;
    content: string;
    created_at: string;
}

export function UserStoriesGenerator() {
    const [featureDesc, setFeatureDesc] = useState('');
    const [generatedStories, setGeneratedStories] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [savedStories, setSavedStories] = useState<SavedStories[]>([]);
    const [copied, setCopied] = useState(false);
    const [selectedStory, setSelectedStory] = useState<SavedStories | null>(null);
    const { theme } = useTheme();
    const navigate = useNavigate();

    useEffect(() => {
        const fetchUserAndStories = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (user) {
                const { data, error } = await supabase
                    .from('user_stories')
                    .select('*')
                    .eq('user_id', user.id)
                    .order('created_at', { ascending: false });

                if (data && !error) {
                    setSavedStories(data);
                }
            } else {
                navigate('/auth');
            }
        };
        fetchUserAndStories();

        const prdContext = localStorage.getItem('prd_context_for_stories');
        if (prdContext) {
            setFeatureDesc(prdContext);
            localStorage.removeItem('prd_context_for_stories');
        }
    }, [navigate]);

    const handleGenerate = async () => {
        if (!featureDesc.trim()) return;
        setLoading(true); setError(null); setGeneratedStories(''); setSelectedStory(null);
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) throw new Error('You must be logged in to generate stories');

            const result = await generateUserStories(featureDesc);
            setGeneratedStories(result);

            const { data, error } = await supabase
                .from('user_stories')
                .insert([{
                    user_id: user.id,
                    feature: featureDesc,
                    content: result
                }])
                .select()
                .single();

            if (error) throw error;
            if (data) {
                setSavedStories([data, ...savedStories]);
            }
        } catch (err) { setError(err instanceof Error ? err.message : 'Failed to generate user stories'); }
        finally { setLoading(false); }
    };

    const handleCopy = async () => { await navigator.clipboard.writeText(selectedStory?.content || generatedStories); setCopied(true); setTimeout(() => setCopied(false), 2000); };
    
    const handleDownload = () => {
        const content = selectedStory?.content || generatedStories;
        const feature = selectedStory?.feature || featureDesc;
        const element = document.createElement('div');
        element.innerHTML = `<div style="padding: 40px; font-family: sans-serif; color: #333; line-height: 1.6;"><h1 style="color: #ef4444; border-bottom: 2px solid #ef4444; padding-bottom: 10px;">User Stories: ${feature}</h1><p style="color: #666; font-size: 12px;">Generated by 3.0 Labs PM Agent on ${new Date().toLocaleDateString()}</p><div style="margin-top: 20px; white-space: pre-wrap;">${content}</div></div>`;
        const opt = { margin: 10, filename: `UserStories-${feature.substring(0, 30).replace(/[^a-zA-Z0-9]/g, '_')}.pdf`, image: { type: 'jpeg' as 'jpeg', quality: 0.98 }, html2canvas: { scale: 2 }, jsPDF: { unit: 'mm' as 'mm', format: 'a4' as 'a4', orientation: 'portrait' as 'portrait' } };
        html2pdf().set(opt).from(element).save();
    };

    const handleDelete = async (id: string) => {
        try {
            const { error } = await supabase.from('user_stories').delete().eq('id', id);
            if (error) throw error;
            setSavedStories(savedStories.filter(s => s.id !== id));
            if (selectedStory?.id === id) { setSelectedStory(null); setGeneratedStories(''); }
        } catch (err) {
            setError('Failed to delete user story');
        }
    };

    const displayContent = selectedStory?.content || generatedStories;

    return (
        <>
            <div className="flex-1 flex flex-col h-screen overflow-hidden relative px-0 sm:px-0">
                <div className="absolute inset-0 flex items-center justify-center pointer-events-none overflow-hidden z-0 select-none">
                    <div className="text-[20vw] font-black text-red-500/[0.03] whitespace-nowrap leading-none tracking-tighter transform -rotate-12 select-none animate-pulse-slow">
                        3.0LABS
                    </div>
                </div>

                <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-red-600/20 rounded-full blur-[120px] animate-float pointer-events-none" />
                <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-80 h-80 bg-red-900/20 rounded-full blur-[100px] animate-float-slow pointer-events-none" />
                <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-red-500/50 to-transparent animate-shimmer z-20" />
                <header className={`flex flex-col sm:flex-row items-start sm:items-center justify-between px-4 md:px-10 py-4 sm:py-6 backdrop-blur-xl border-b z-30 flex-shrink-0 gap-2 ${theme === 'dark' ? 'bg-[#0B0C10]/80 border-red-500/10' : 'bg-white/80 border-slate-200'}`}>
                    <div><h1 className={`text-xl sm:text-2xl font-bold tracking-tight flex items-center gap-3 ${theme === 'dark' ? 'text-white' : 'text-slate-900'}`}><Users className="w-6 h-6 sm:w-7 sm:h-7 text-red-500 animate-pulse" />User Stories Generator</h1>
                        <p className="text-gray-400 text-xs sm:text-sm mt-1">Generate user stories with acceptance criteria and story points</p></div>
                </header>

                <div className="flex-1 flex flex-col xl:flex-row overflow-hidden">
                    <div className="flex-1 overflow-y-auto px-4 md:px-10 py-8 z-10 custom-scrollbar">
                        <div className="mb-8 p-4 sm:p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl animate-fade-in-up">
                            <label className="block font-semibold text-white text-lg mb-3">Describe the feature</label>
                            <textarea value={featureDesc} onChange={e => setFeatureDesc(e.target.value)} placeholder="e.g. User authentication with SSO, password recovery, and 2FA..." className="w-full h-32 px-4 py-3 bg-black/40 border border-white/10 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/50 text-white placeholder-gray-600 resize-none" />
                            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mt-4 gap-3">
                                <span className="text-xs text-gray-500">{featureDesc.length} chars</span>
                                <button onClick={handleGenerate} disabled={loading || !featureDesc.trim()} className="w-full sm:w-auto px-8 py-3 bg-gradient-to-r from-red-600 to-red-800 text-white font-semibold rounded-xl shadow-[0_0_20px_rgba(239,68,68,0.3)] hover:shadow-[0_0_30px_rgba(239,68,68,0.5)] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2">
                                    {loading ? <><div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />Generating...</> : <><Sparkles className="w-5 h-5" />Generate Stories</>}
                                </button>
                            </div>
                        </div>
                        {error && <div className="mb-6 p-4 bg-red-500/10 border border-red-500/30 text-red-400 rounded-xl flex items-center justify-between uppercase text-xs font-bold tracking-widest"><span>{error}</span><button onClick={() => setError(null)}>&times;</button></div>}
                        {displayContent && !loading && (
                            <div className="mb-8 p-4 sm:p-6 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl animate-fade-in-up">
                                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-4 gap-2">
                                    <div className="font-semibold text-red-500 text-lg flex items-center"><div className="w-2 h-2 bg-red-600 rounded-full mr-3 animate-pulse" />{selectedStory ? `Stories: ${selectedStory.feature.substring(0, 40)}...` : 'Generated User Stories'}</div>
                                    <div className="flex flex-wrap gap-2">
                                        <button onClick={handleCopy} className="p-2 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg" title="Copy"><Copy className="w-4 h-4" /></button>
                                        <button onClick={handleDownload} className="p-2 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg" title="Download"><Download className="w-4 h-4" /></button>
                                    </div>
                                </div>
                                {copied && <div className="mb-3 text-sm text-emerald-400">Γ£ô Copied!</div>}
                                <div className="text-gray-300 leading-relaxed whitespace-pre-wrap text-sm">{displayContent}</div>
                            </div>
                        )}
                    </div>
                    <aside className="hidden xl:flex w-full xl:w-80 bg-[#0B0C10]/80 backdrop-blur-md border-l border-red-500/10 px-4 sm:px-6 py-8 flex-col z-20 overflow-y-auto custom-scrollbar">
                        <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2"><Clock className="w-5 h-5 text-gray-400" />History</h3>
                        {savedStories.length === 0 ? <div className="text-gray-500 text-sm text-center py-8">No stories yet</div> :
                            <div className="space-y-3">{savedStories.map(s => (
                                <div key={s.id} className={`p-4 rounded-xl border cursor-pointer transition-all group ${selectedStory?.id === s.id ? 'bg-red-500/10 border-red-500/30' : 'bg-white/5 border-white/10 hover:bg-white/[0.07]'}`} onClick={() => { setSelectedStory(s); setGeneratedStories(''); }}>
                                    <div className="font-medium text-white text-sm truncate mb-1">{s.feature}</div>
                                    <div className="text-xs text-gray-500 flex items-center justify-between"><span>{new Date(s.created_at).toLocaleDateString()}</span>
                                        <button onClick={e => { e.stopPropagation(); handleDelete(s.id); }} className="p-1 text-gray-500 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"><Trash2 className="w-3.5 h-3.5" /></button>
                                    </div>
                                </div>
                            ))}</div>}
                    </aside>
                </div>
            </div>
            <style>{`
                .custom-scrollbar::-webkit-scrollbar { width: 4px; }
                .custom-scrollbar::-webkit-scrollbar-track { background: rgba(255, 255, 255, 0.02); }
                .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.1); border-radius: 10px; }
                .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(255, 255, 255, 0.2); }
            `}</style>
        </>
    );
}
